// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
// / import 'firebase_options.dart';
    show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCYBoKQ_u79N7XNieUyiJ1u4-bzPspWA',
    appId: '1:489371013200:web:73568099d9b8e269bc4155',
    messagingSenderId: '489371013200',
    projectId: 'ehub-15d4a',
    authDomain: 'ehub-15d4a.firebaseapp.com',
    databaseURL: 'https://ehub-15d4a.firebaseio.com',
    storageBucket: 'ehub-15d4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGknpoAoQcSwasnEP89Ox2PlF2aVbliE',
    appId: '1:489371013200:android:74e3b9e51454410a',
    messagingSenderId: '489371013200',
    projectId: 'ehub-15d4a',
    databaseURL: 'https://ehub-15d4a.firebaseio.com',
    storageBucket: 'ehub-15d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi4Y0NBF03x7q_MDP798_UxBOL18ArLKY',
    appId: '1:489371013200:ios:6133705c51655360bc4155',
    messagingSenderId: '489371013200',
    projectId: 'ehub-15d4a',
    databaseURL: 'https://ehub-15d4a.firebaseio.com',
    storageBucket: 'ehub-15d4a.appspot.com',
    androidClientId:
        '489371013200-49dq5kitom2f56hj79s6nlgir0lefjpp.apps.googleusercontent.com',
    iosClientId:
        '489371013200-ln021rpkecvg4mq3ocid8tb4hm68nn2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventhub',
  );
}
